from app import mail
from flask_mail import Message
from flask import current_app

def send_mail(recipients, subject, body=None, sender_name=None, sender_email=None):
    sender = current_app.config.get("MAIL_DEFAULT_SENDER")
    if sender_name:
        sender = (sender_name, sender[1])
    if sender_email:
        sender = (sender[0], sender_email)

    msg = Message(subject=subject, recipients=recipients, sender=sender)
    
    msg.html=f"""{body} <hr>This message was automatically generated by our system and send from a <i>no-replay</i> adress. If you have any questions, feel free to contact us.<br /> The PrusMoot Team"""
    
    mail.send(msg)